### ISSUE TITLE
Fix testcase for win32 - To-Do 07.08.19

### ISSUE THREAD

**Issue by A7exSchin** [klibio/io.klib.tools#10]
Fix var USERPROFILE, SYSTEMDrive, SYSTEMRoot, TEMP/TMP#

Check out Java 8 Doc ProcessBuilder to fix the vars. Make tests runnable. Run Tests as Gradle Task

**Comment by A7exSchin** [comment]
added vars to env, incl. path
still no process found error

**Comment by peterkir** [comment]
Evaluate how to set a conditional breakpoint in Eclipse to identify the source reason.

**Comment by A7exSchin** [comment]
Debug with sigar code 1.6.4

Threading Issue?
