### ISSUE TITLE
Setup Raspi k8s cluster

### ISSUE THREAD

**Issue by peterkir** [klibio/io.klib.tools#31]
Expected result:
Raspi Cluster is setup with k8s (1 master - 3 worker)
https://kubernetes.io/docs/setup/

e.g. links
https://github.com/teamserverless/k8s-on-raspbian/blob/master/GUIDE.md
https://medium.com/nycdev/k8s-on-pi-9cc14843d43
https://itnext.io/building-a-kubernetes-cluster-on-raspberry-pi-and-low-end-equipment-part-1-a768359fbba3

**Comment by A7exSchin** [comment]
DOR:
Create a kubernetes cluster for a running truck stack

**Comment by A7exSchin** [comment]
https://github.com/TheECanyon/klib.cluster
